# SPDX-FileCopyrightText: 2020 Melissa LeBlanc-Williams
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Versions
      run: |
        python3 --version
    - name: Checkout Current Repo
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext
        pip install -r requirements.txt
    - name: Checkout Henner Zeller RGB LED Matrix Library
      uses: actions/checkout@v4
      with:
        repository: hzeller/rpi-rgb-led-matrix
        path: rpi-rgb-led-matrix
    - name: Compile RGB Matrix Library Python Bindings
      working-directory: ./rpi-rgb-led-matrix/bindings/python/
      run: |
        make build-python PYTHON=$(which python3)
        sudo make install-python PYTHON=$(which python3)
    - name: Install ruff, reuse, & Sphinx
      run: |
        pip install --force-reinstall ruff reuse Sphinx sphinx-rtd-theme
    - name: Library version
      run: git describe --dirty --always --tags
    - name: Check formatting
      run: |
        ruff format --check
    - name: Lint
      run: |
        ruff check
    - name: Check License Compliance
      run: |
        reuse lint
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
