name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check For setup.py
      id: need-pypi
      run: |
        echo ::set-output name=setup-py::$( find . -wholename './setup.py' )
    - name: Set up Python
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Checkout Henner Zeller RGB LED Matrix Library
      uses: actions/checkout@v2
      with:
        repository: hzeller/rpi-rgb-led-matrix
        path: rpi-rgb-led-matrix
    - name: Install dependencies
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Compile RGB Matrix Library Python Binding
      working-directory: ./rpi-rgb-led-matrix/bindings/python/
      run: |
        make build-python PYTHON=$(which python3)
        sudo make install-python PYTHON=$(which python3)
    - name: Build and publish
      if: contains(steps.need-pypi.outputs.setup-py, 'setup.py')
      env:
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python setup.py sdist
        twine upload dist/*
